--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/v3rtz/.config/hypr/wallpapers/anime_skyline.png"

-- Special
background="#081430"
foreground="#c1c4cb"
cursor="#c1c4cb"

-- Colors
color0="#081430"
color1="#6e5787"
color2="#7c507b"
color3="#a75476"
color4="#745796"
color5="#5760a6"
color6="#b0697f"
color7="#92969d"
color8="#606675"
color9="#9375B5"
color10="#A66BA4"
color11="#DF719E"
color12="#9B74C9"
color13="#7581DE"
color14="#EB8DAA"
color15="#c1c4cb"
