[colors.primary]
background = "#081430"
foreground = "#c1c4cb"

[colors.cursor]
text = "#081430"
cursor = "#c1c4cb"

[colors.vi_mode_cursor]
text = "#081430"
cursor = "#c1c4cb"

[colors.search.matches]
foreground = "#081430"
background = "#c1c4cb"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#606675"
background = "#92969d"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#081430"
red = "#6e5787"
green = "#7c507b"
yellow = "#a75476"
blue = "#745796"
magenta = "#5760a6"
cyan = "#b0697f"
white = "#92969d"

[colors.bright]
black = "#606675"
red = "#9375B5"
green = "#A66BA4"
yellow = "#DF719E"
blue = "#9B74C9"
magenta = "#7581DE"
cyan = "#EB8DAA"
white = "#c1c4cb"

[colors.dim]
black = "#c1c4cb"
red = "#9375B5"
green = "#7581DE"
yellow = "#DF719E"
blue = "#9B74C9"
magenta = "#A66BA4"
cyan = "#EB8DAA"
white = "#606675"

